### ISSUE TITLE
Newline suggestion

### ISSUE THREAD

**Issue by JanezCim** [UrbanBobek/cow-wisdom#1]
Live saver this cow!

Can I suggest that you add a simple newline before the first line in your script: 
https://github.com/UrbanBobek/cow-wisdom/blob/c7ef7f1337c004f5d51ca1f443ffad468a7708d7/bashrc_commands.txt#L1

So that when I execute  ` cat  bashrc_commands.txt >> ~/.bashrc` i have an empty line first and then the first line, just makes it nicer to look at :>

**Comment by UrbanBobek** [comment]
Great suggestion! I added a new line.
